version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    ports:
      - "3000:3000"
      # - "3000:80" - use it if you want to use nginx for production environment
    environment:
      - API_URL=http://localhost:3001
